import I18n from '../../i18n/i18n'

export const RELATIVE_FACE_PATH = 'face.jpg'

export const getAgreementText = () => {
  return (
    I18n.t('privacy_policy_intro_01') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_intro_02') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_intro_03') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_intro_04') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_intro_05') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_01') +
    '\n' +
    I18n.t('privacy_policy_body_01_01') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_01_02') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_01_03') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_01_04') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_02') +
    '\n' +
    I18n.t('privacy_policy_body_02_01') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_03') +
    '\n' +
    I18n.t('privacy_policy_body_03_00') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_03_01') +
    '\n' +
    I18n.t('privacy_policy_body_03_02') +
    '\n' +
    I18n.t('privacy_policy_body_03_03') +
    '\n' +
    I18n.t('privacy_policy_body_03_04') +
    '\n' +
    I18n.t('privacy_policy_body_03_05') +
    '\n' +
    I18n.t('privacy_policy_body_03_06') +
    '\n' +
    I18n.t('privacy_policy_body_03_07') +
    '\n' +
    I18n.t('privacy_policy_body_03_08') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_04') +
    '\n' +
    I18n.t('privacy_policy_body_04_00') +
    '\n' +
    I18n.t('privacy_policy_body_04_01') +
    '\n' +
    I18n.t('privacy_policy_body_04_02') +
    '\n' +
    I18n.t('privacy_policy_body_04_03') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_04_04') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_05') +
    '\n' +
    I18n.t('privacy_policy_body_05_00') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_06') +
    '\n' +
    I18n.t('privacy_policy_body_06_00') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_07') +
    '\n' +
    I18n.t('privacy_policy_body_07_00') +
    '\n' +
    I18n.t('privacy_policy_body_07_01') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_08') +
    '\n' +
    I18n.t('privacy_policy_body_08_00') +
    '\n' +
    I18n.t('privacy_policy_body_08_01') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_09') +
    '\n' +
    I18n.t('privacy_policy_body_09_00') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_body_10') +
    '\n' +
    I18n.t('privacy_policy_body_10_00') +
    '\n' +
    I18n.t('privacy_policy_dga_contact_name') +
    '\n' +
    I18n.t('privacy_policy_dga_contact_address_01') +
    '\n' +
    I18n.t('privacy_policy_dga_contact_address_02') +
    '\n' +
    I18n.t('privacy_policy_dga_contact_tel') +
    I18n.t('privacy_policy_dga_contact_email') +
    '\n' +
    I18n.t('privacy_policy_contact_call_center') +
    '\n' +
    I18n.t('privacy_policy_ending01') +
    '\n' +
    '\n' +
    I18n.t('privacy_policy_ending02') +
    '\n' +
    I18n.t('privacy_policy_version')
  )
}
