import { YESNO_QUESTIONS } from './const'

export { YESNO_QUESTIONS }
export const dataInputTable: DataInput[] = [
  {
    id: 'dob',
    name: 'data:demographic:dob',
    title: 'Date of birth',
    titleTH: 'วันเกิด',
    dataType: 'String',
    required: true,
    inputType: 'Date',
    // defaultValue: moment().subtract(18, 'year').format('YYYY-MM-DD')
  },
  {
    id: 'gender',
    name: 'data:demographic:gender',
    title: 'Gender',
    titleTH: 'เพศ',
    dataType: 'String',
    required: true,
    inputType: 'M/F',
  },
  {
    id: 'nationality',
    name: 'data:demographic:nationality',
    title: 'Nationality',
    titleTH: 'สัญชาติ',
    dataType: 'String',
    required: true,
    inputType: 'Select <Nationality>',
  },
  {
    id: 'firstname',
    name: 'data:id:firstname',
    title: 'First name',
    titleTH: 'ชื่อจริง',
    dataType: 'String',
    required: true,
    inputType: 'Text Single Line',
  },
  {
    id: 'lastname',
    name: 'data:id:lastname',
    title: 'Last name',
    titleTH: 'นามสกุล',
    dataType: 'String',
    required: true,
    inputType: 'Text Single Line',
  },
  {
    id: 'nationalId',
    name: 'data:id:nationalId',
    title: 'National ID',
    titleTH: 'เลขประจำตัวประชาชน',
    dataType: 'String',
    required: true,
    inputType: 'Text <National ID>',
  },
  {
    id: 'mobile',
    name: 'data:id:mobile',
    title: 'Mobile Number',
    titleTH: 'เบอร์โทร',
    dataType: 'String',
    required: true,
    inputType: 'Text <Phone Number>',
  },
  {
    id: 'email',
    name: 'data:id:email',
    title: 'Email',
    titleTH: 'อีเมล',
    dataType: 'String',
    required: false,
    inputType: 'Text <Email>',
  },
  {
    id: 'symptom1',
    titleTH: YESNO_QUESTIONS.symptom1,
    name: 'data:covid:symptom1',
    dataType: 'Boolean',
    required: true,
    inputType: 'มี/ไม่มี',
  },
  {
    id: 'symptom2',
    titleTH: YESNO_QUESTIONS.symptom2,
    name: 'data:covid:symptom2',
    dataType: 'Boolean',
    required: true,
    inputType: 'มี/ไม่มี',
  },
  {
    id: 'travel1',
    titleTH: YESNO_QUESTIONS.travel1,
    name: 'data:travel:travel1',
    dataType: 'Boolean',
    required: true,
    inputType: 'ไปมา/ไม่ไป',
  },
  {
    id: 'travel2',
    titleTH: YESNO_QUESTIONS.travel2,
    name: 'data:travel:travel2',
    dataType: 'Boolean',
    required: true,
    inputType: 'ไปมา/ไม่ไป',
  },
  {
    id: 'travel2a',
    name: 'data:travel:travel2:country',
    titleTH: 'ประเทศที่คุณเพิ่งเดินทางกลับมาในช่วง 14 วันที่ผ่านมา',
    dataType: 'String',
    required: true,
    inputType: 'Select <Country>',
    showCondition: values => {
      return values['travel2']?.toLowerCase() === 'true'
    },
  },
  {
    id: 'travel3',
    titleTH: YESNO_QUESTIONS.travel3,
    name: 'data:travel:travel3',
    dataType: 'Boolean',
    required: true,
    inputType: 'ไปมา/ไม่ไป',
  },
  {
    id: 'community1',
    titleTH: YESNO_QUESTIONS.community1,
    name: 'data:community:community1',
    dataType: 'Boolean',
    required: true,
    inputType: 'มี/ไม่มี',
  },
  {
    id: 'community2',
    titleTH: YESNO_QUESTIONS.community2,
    name: 'data:community:community2',
    dataType: 'Boolean',
    required: true,
    inputType: 'ใช่/ไม่ใช่',
  },
  {
    id: 'community3',
    titleTH: YESNO_QUESTIONS.community3,
    name: 'data:community:community3',
    dataType: 'Boolean',
    required: true,
    inputType: 'ใช่/ไม่ใช่',
  },
]
