# Uncomment the next line to define a global platform for your project
platform :ios, "10.0"

require_relative "../node_modules/@react-native-community/cli-platform-ios/native_modules"

target "ThaiAlert" do
  # Pods for ThaiAlert
  permissions_path = "../node_modules/react-native-permissions/ios"
  pod "FBLazyVector", :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod "FBReactNativeSpec", :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod "RCTRequired", :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod "RCTTypeSafety", :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod "React", :path => "../node_modules/react-native/"
  pod "React-Core", :path => "../node_modules/react-native/"
  pod "React-CoreModules", :path => "../node_modules/react-native/React/CoreModules"
  pod "React-Core/DevSupport", :path => "../node_modules/react-native/"
  pod "React-RCTActionSheet", :path => "../node_modules/react-native/Libraries/ActionSheetIOS"
  pod "React-RCTAnimation", :path => "../node_modules/react-native/Libraries/NativeAnimation"
  pod "React-RCTBlob", :path => "../node_modules/react-native/Libraries/Blob"
  pod "React-RCTImage", :path => "../node_modules/react-native/Libraries/Image"
  pod "React-RCTLinking", :path => "../node_modules/react-native/Libraries/LinkingIOS"
  pod "React-RCTNetwork", :path => "../node_modules/react-native/Libraries/Network"
  pod "React-RCTSettings", :path => "../node_modules/react-native/Libraries/Settings"
  pod "React-RCTText", :path => "../node_modules/react-native/Libraries/Text"
  pod "React-RCTVibration", :path => "../node_modules/react-native/Libraries/Vibration"
  pod "React-Core/RCTWebSocket", :path => "../node_modules/react-native/"
  pod "React-ART", :path => "../node_modules/react-native/Libraries/ART"

  pod "React-cxxreact", :path => "../node_modules/react-native/ReactCommon/cxxreact"
  pod "React-jsi", :path => "../node_modules/react-native/ReactCommon/jsi"
  pod "React-jsiexecutor", :path => "../node_modules/react-native/ReactCommon/jsiexecutor"
  pod "React-jsinspector", :path => "../node_modules/react-native/ReactCommon/jsinspector"
  pod "ReactCommon/callinvoker", :path => "../node_modules/react-native/ReactCommon"
  pod "ReactCommon/turbomodule/core", :path => "../node_modules/react-native/ReactCommon"
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  pod "DoubleConversion", :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod "glog", :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec"
  pod "Folly", :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  # Permissions
  pod "Permission-LocationAlways", :path => "#{permissions_path}/LocationAlways.podspec"
  pod "Permission-Motion", :path => "#{permissions_path}/Motion.podspec"
  pod "Permission-Camera", :path => "#{permissions_path}/Camera.podspec"

  # React Native Maps dependencies
  rn_maps_path = "../node_modules/react-native-maps"
  pod "react-native-maps", :path => rn_maps_path
  pod "react-native-google-maps", :path => rn_maps_path
  pod "GoogleMaps"
  pod "Google-Maps-iOS-Utils"

  use_native_modules!

  pod "react-native-image-editor", :path => "../node_modules/@react-native-community/image-editor"

  pod "rn-fetch-blob", :path => "../node_modules/rn-fetch-blob"
  
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
  
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
end
