require_relative '../node_modules/react-native/scripts/react_native_pods'
# Uncomment the next line to define a global platform for your project
platform :ios, "10.0"

require_relative "../node_modules/@react-native-community/cli-platform-ios/native_modules"

target "ThaiAlert" do
  # Pods for ThaiAlert
  config = use_native_modules!

  permissions_path = "../node_modules/react-native-permissions/ios"

  use_react_native!(:path => config["reactNativePath"])
  # Permissions
  pod "Permission-LocationAlways", :path => "#{permissions_path}/LocationAlways.podspec"
  pod "Permission-Motion", :path => "#{permissions_path}/Motion.podspec"
  pod "Permission-Camera", :path => "#{permissions_path}/Camera.podspec"

end
