# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require "dotenv"

before_all do
  Dotenv.overload "../../.env"
end

default_platform(:ios)

platform :ios do
  desc "Push a new release build to TestFlight"
  lane :beta do
    set_info_plist_value(path: "ThaiAlert/Info.plist", key: "CodePushDeploymentKey", value: "#{ENV["CODE_PUSH_IOS"]}")
    increment_build_number(xcodeproj: "ThaiAlert.xcodeproj")
    match(type: "appstore")
    build_app(
      workspace: "ThaiAlert.xcworkspace",
      scheme: "ThaiAlert Release",
      include_bitcode: true,
    )
    set_info_plist_value(path: "ThaiAlert/Info.plist", key: "CodePushDeploymentKey", value: "")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
